name: stock-price-forecasting
channels:
- conda-forge
- defaults
dependencies:
- h5py=2.7.1=py36_1
- hdf5=1.8.18=0
- keras=2.0.6=py36_0
- mock=2.0.0=py36_0
- pbr=3.1.1=py36_0
- protobuf=3.3.2=py36_0
- pyyaml=3.12=py36_1
- tensorflow=1.0.0=py36_0
- yaml=0.1.6=0
- appnope=0.1.0=py36hf537a9a_0
- asn1crypto=0.22.0=py36hb705621_1
- attrs=15.2.0=py36_0
- automat=0.5.0=py36_0
- bleach=2.0.0=py36h8fcea71_0
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.7.27.1=py36hd973bb6_0
- cffi=1.10.0=py36h880867e_1
- chardet=3.0.4=py36h96c241c_1
- constantly=15.1.0=py36_0
- cryptography=2.0.3=py36h22d4226_1
- cssselect=1.0.1=py36_0
- cycler=0.10.0=py36hfc81398_0
- dbus=1.10.22=h50d9ad6_0
- decorator=4.1.2=py36h69a1b52_0
- entrypoints=0.2.3=py36hd81d71f_2
- expat=2.2.4=h8f26bf8_1
- freetype=2.8=h143eb01_0
- gettext=0.19.8.1=hb0f4f8b_2
- glib=2.53.6=ha08cb78_1
- html5lib=0.999999999=py36h79312fd_0
- hyperlink=17.1.1=py36_0
- icu=58.2=hea21ae5_0
- idna=2.6=py36h8628d0a_1
- incremental=16.10.1=py36_0
- intel-openmp=2018.0.0=hdd0ccc9_7
- ipykernel=4.6.1=py36h3208c25_0
- ipython=6.1.0=py36hf612aae_1
- ipython_genutils=0.2.0=py36h241746c_0
- ipywidgets=7.0.0=py36h24d3910_0
- jedi=0.10.2=py36h6325097_0
- jinja2=2.9.6=py36hde4beb4_1
- jpeg=9b=haccd157_1
- jsonschema=2.6.0=py36hb385e00_0
- jupyter=1.0.0=py36h598a6cc_0
- jupyter_client=5.1.0=py36hf6c435f_0
- jupyter_console=5.2.0=py36hccf5b1c_1
- jupyter_core=4.3.0=py36h93810fe_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=hd939716_3
- libgfortran=3.0.1=h93005f0_2
- libiconv=1.15=h99df5da_5
- libpng=1.6.32=hce72d48_2
- libsodium=1.0.13=hba5e272_2
- libtiff=4.0.8=h8cd0352_9
- libxml2=2.9.4=hbd0960b_5
- libxslt=1.1.29=h95a2935_5
- lxml=3.8.0=py36h1003d81_0
- markupsafe=1.0=py36h3a1e703_1
- matplotlib=2.0.2=py36h507e440_1
- mistune=0.7.4=py36hccd6237_0
- mkl=2018.0.0=hc285769_4
- nbconvert=5.3.1=py36h810822e_0
- nbformat=4.4.0=py36h827af21_0
- ncurses=6.0=ha932d30_1
- notebook=5.0.0=py36h462289e_2
- numpy=1.13.1=py36h93d791d_2
- olefile=0.44=py36ha08bf50_0
- openssl=1.0.2l=h57f3a61_2
- pandas=0.20.3=py36hd6655d8_2
- pandas-datareader=0.5.0=py36_0
- pandoc=1.19.2.1=ha5e8f32_1
- pandocfilters=1.4.2=py36h3b0b094_1
- parsel=1.2.0=py36_0
- patsy=0.4.1=py36ha1b3fa5_0
- pcre=8.41=h29eefc5_0
- pexpect=4.2.1=py36h3eac828_0
- pickleshare=0.7.4=py36hf512f8e_0
- pillow=4.2.1=py36h0263179_0
- pip=9.0.1=py36hbd95645_3
- prompt_toolkit=1.0.15=py36haeda067_0
- ptyprocess=0.5.2=py36he6521c3_0
- pyasn1=0.2.3=py36_0
- pyasn1-modules=0.0.8=py36_0
- pycparser=2.18=py36h724b2fc_1
- pydispatcher=2.0.5=py36_0
- pygments=2.2.0=py36h240cd3f_0
- pyopenssl=17.2.0=py36h5d7bf08_0
- pyparsing=2.2.0=py36hb281f35_0
- pyqt=5.6.0=py36he5c6137_6
- pysocks=1.6.7=py36hfa33cec_1
- python=3.6.2=ha11d96e_18
- python-dateutil=2.6.1=py36h86d2abb_1
- pytz=2017.2=py36h2e7dfbc_1
- pyzmq=16.0.2=py36h087ffad_2
- qt=5.6.2=h9975529_14
- qtconsole=4.3.1=py36hd96c0ff_0
- queuelib=1.4.2=py36_0
- readline=7.0=h81b24a6_3
- requests=2.18.4=py36h4516966_1
- requests-file=1.4.1=py36_0
- requests-ftp=0.3.1=py36_0
- scikit-learn=0.19.0=py36h4cafacf_2
- scipy=0.19.1=py36h3e758e1_3
- scrapy=1.3.3=py36_0
- seaborn=0.8.0=py36h74df97e_0
- service_identity=17.0.0=py36_0
- setuptools=36.5.0=py36h2134326_0
- simplegeneric=0.8.1=py36he5b5b09_0
- sip=4.18.1=py36h2824476_2
- six=1.10.0=py36h1d5bd22_1
- sqlite=3.20.1=h900c3b0_1
- statsmodels=0.8.0=py36h9c68fc9_0
- terminado=0.6=py36h656782e_0
- testpath=0.3.1=py36h625a49b_0
- tk=8.6.7=hcdce994_1
- tornado=4.5.2=py36h468dda9_0
- traitlets=4.3.2=py36h65bd3ce_0
- twisted=17.5.0=py36_0
- urllib3=1.22=py36h68b9469_0
- w3lib=1.17.0=py36_0
- wcwidth=0.1.7=py36h8c6ec74_0
- webencodings=0.5.1=py36h3b9701d_1
- wheel=0.29.0=py36h3597b6d_1
- widgetsnbextension=3.0.2=py36h91f43ea_1
- xz=5.2.3=ha24016e_1
- zeromq=4.2.2=h131e0f7_1
- zlib=1.2.11=h60db283_1
- zope=1.0=py36_0
- zope.interface=4.4.2=py36_0
- pip:
  - furl==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - nanocut==12.12
  - orderedmultidict==0.7.11
  - prompt-toolkit==1.0.15
  - service-identity==17.0.0
prefix: /Users/jeremyjordan/anaconda/envs/stock-price-forecasting

